### ISSUE TITLE
I have Raspbian OS on Raspberry Pi 3. How can I install it...

### ISSUE THREAD

**Issue by a-belard** [koenvervloesem/bazel-on-arm#11]

**Comment by koenvervloesem** [comment]
Have you read the [README](https://github.com/koenvervloesem/bazel-on-arm#usage=)?

**Comment by a-belard** [comment]
Yeah, I saw it was tested on raspberry pi 4, but not working on raspberry
pi 3

**Comment by koenvervloesem** [comment]
Just try it and let me know when it doesn't work.

**Comment by a-belard** [comment]
Yeah, I tried building it myself, using pre-built binary, but none working

**Comment by koenvervloesem** [comment]
If you want some help, please add detailed output with the exact error messages.

**Comment by bzgec** [comment]
When I run `make bazel` I get `The system is out of resources.` error:

```
The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:400)
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:413)
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:418)
	at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:182)
	at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:198)
	at java.base/java.nio.file.Files$2.hasNext(Files.java:3708)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager$DirectoryContainer.list(JavacFileManager.java:455)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:719)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.list(ClassFinder.java:737)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.scanUserPaths(ClassFinder.java:687)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:551)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:299)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder$$Lambda$44/0x63e7a228.complete(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$PackageSymbol.members(Symbol.java:1131)
	at jdk.compiler/com.sun.tools.javac.code.Symtab.listPackageModules(Symtab.java:837)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.visitTopLevel(Enter.java:345)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:529)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.classEnter(Enter.java:286)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.classEnter(Enter.java:301)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.complete(Enter.java:576)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.main(Enter.java:560)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1062)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:937)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
```

I also tried pre-built binay (v4.2.2), which returns version but running a test fails with:
```
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/google/googletest/archive/58d77fa8070e8cec2dc1ed015d66b454c8d78850.zip) = ab78fa3f912d44d38b785ec011a25f26512aaedc5291f51f3807c592b506d33a
DEBUG: Rule 'googletest' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "ab78fa3f912d44d38b785ec011a25f26512aaedc5291f51f3807c592b506d33a"
DEBUG: Repository googletest instantiated at:
  /home/bzgec/battTester_FW/mdls/WORKSPACE:6:13: in <toplevel>
Repository rule http_archive defined at:
  /home/bzgec/.cache/bazel/_bazel_bzgec/4541f1504de36abb2d9e1610aa3fa596/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/bzgec/.cache/bazel/_bazel_bzgec/4541f1504de36abb2d9e1610aa3fa596/external/bazel_tools/tools/jdk/BUILD:490:6: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment, please explicitly provide one using `--host_javabase.`
INFO: Repository remote_java_tools_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:223:6: in <toplevel>
  /home/bzgec/.cache/bazel/_bazel_bzgec/4541f1504de36abb2d9e1610aa3fa596/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /home/bzgec/.cache/bazel/_bazel_bzgec/4541f1504de36abb2d9e1610aa3fa596/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
```

Running on:
- `Raspbian GNU/Linux 11.4 (bullseye) - 32bit Lite`
- `Raspberry Pi 3 Model B Rev 1.2`

**Comment by Bagavath-G** [comment]
> If you want some help, please add detailed output with the exact error messages.

Hi, I tried to build in Raspberry pi 3 (Buster -32bit). 

Below error for your reference.

The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space

Can you please help me?

Thanks in advance

Regards,
Bagavath
